// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ACT.Core.Types.PluginPackage;
//
//    var actExamplePackageConfig = ActExamplePackageConfig.FromJson(jsonString);

namespace ACT.Core.Types.PluginPackage
{
    public interface I_Plugin_Package_Configuration
    {
        Guid? PackageId { get; set; }
        string PackageName { get; set; }
        string CertificationHash { get; set; }
        string IAuthorInfo { get; set; }

        I_PluginPackage_Basic_Configuration PluginPackage_ConfigurationData { get; set; }                
        List<I_Plugin_Package_InterfaceTypes> Implemented_Interface_Types { get; set; }
                
        Interfaces.Security.I_Author ProcessAuthorData();
        List<Type> GetAllImplementedTypes();
    }
}