// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ACT.Core.Types.PluginPackage;
//
//    var actExamplePackageConfig = ActExamplePackageConfig.FromJson(jsonString);

namespace ACT.Core.Types.PluginPackage
{
    public interface I_Plugin_Package_InterfaceTypes
    {
        string IAuthorInfo { get; set; }
        Interfaces.Security.I_Author ProcessAuthorData();

        string DllFileName { get; set; }
        string FullClassName { get; set; }

        string EncryptionMethod { get; set; }
        bool? EncryptSystemConfigurationValuesFile { get; set; }

        bool? Append_System_ConfigurationValues { get; set; }
        string ACT_SystemConfiguration_AppendingValues_Filename { get; set; }

        string Interface_Fullname { get; set; }
        string Interface_Shortname { get; set; }

        Type GetTypeInformation();

        List<Interfaces.Common.I_CustomNameValueData> AdditionalData { get; set; }
    }
}