// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using ACT.Core.Types.PluginPackage;
//
//    var actExamplePackageConfig = ActExamplePackageConfig.FromJson(jsonString);

using ACT.Core.Interfaces.Common;

namespace ACT.Core.Interfaces.Plugins
{
    public interface I_Plugin_Package_InterfaceTypes : Plugins.I_Plugin
    {
        string IAuthorInfo { get; set; }
        Data.JSON_Contracts.I_Author ProcessAuthorData();

        string DllFileName { get; set; }
        string FullClassName { get; set; }

        string EncryptionMethod { get; set; }
        bool? EncryptSystemConfigurationValuesFile { get; set; }

        bool? Append_System_ConfigurationValues { get; set; }
        string ACT_SystemConfiguration_AppendingValues_Filename { get; set; }

        string Interface_Fullname { get; set; }
        string Interface_Shortname { get; set; }

        Type GetTypeInformation();

        List<Data.I_NameValue_Data> AdditionalData { get; set; }
    }
}